// Copyright (c) Microsoft. All rights reserved.
namespace Microsoft.Azure.Devices.Edge.Util.Edged.GeneratedCode
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Globalization;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Reflection;
    using System.Runtime.CompilerServices;
    using System.Runtime.Serialization;
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

#pragma warning disable // Disable all warnings

    [GeneratedCode("NSwag", "11.17.6.0 (NJsonSchema v9.10.46.0 (Newtonsoft.Json v9.0.0.0))")]
    public partial class HttpWorkloadClient
    {
        private string _baseUrl = "http://";
        private HttpClient _httpClient;
        private Lazy<JsonSerializerSettings> _settings;

        public HttpWorkloadClient(HttpClient httpClient)
        {
            _httpClient = httpClient;
            _settings = new Lazy<JsonSerializerSettings>(
                () =>
                {
                    var settings = new JsonSerializerSettings();
                    UpdateJsonSerializerSettings(settings);
                    return settings;
                });
        }

        public string BaseUrl
        {
            get { return _baseUrl; }
            set { _baseUrl = value; }
        }

        protected JsonSerializerSettings JsonSerializerSettings
        {
            get { return _settings.Value; }
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module on whose behalf the payload will be signed. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <param name="payload">The data to be signed.</param>
        /// <returns>Ok</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        public Task<SignResponse> SignAsync(string api_version, string name, string genid, SignRequest payload)
        {
            return SignAsync(api_version, name, genid, payload, CancellationToken.None);
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module on whose behalf the payload will be signed. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <param name="payload">The data to be signed.</param>
        /// <returns>Ok</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        public async Task<SignResponse> SignAsync(string api_version, string name, string genid, SignRequest payload, CancellationToken cancellationToken)
        {
            if (name == null)
                throw new ArgumentNullException("name");

            if (genid == null)
                throw new ArgumentNullException("genid");

            if (api_version == null)
                throw new ArgumentNullException("api_version");

            var urlBuilder_ = new StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/modules/{name}/genid/{genid}/sign?");
            urlBuilder_.Replace("{name}", WebUtility.UrlEncode(ConvertToString(name, CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{genid}", WebUtility.UrlEncode(ConvertToString(genid, CultureInfo.InvariantCulture)));
            urlBuilder_.Append("api-version=").Append(WebUtility.UrlEncode(ConvertToString(api_version, CultureInfo.InvariantCulture))).Append("&");
            urlBuilder_.Length--;

            var client_ = _httpClient;
            try
            {
                using (var request_ = new HttpRequestMessage())
                {
                    var content_ = new StringContent(JsonConvert.SerializeObject(payload, _settings.Value));
                    content_.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new HttpMethod("POST");
                    request_.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new Uri(url_, UriKind.RelativeOrAbsolute);
                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(SignResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<SignResponse>(responseData_, _settings.Value);
                                return result_;
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }
                        }
                        else if (status_ == "404")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Not Found", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Error", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }

                        return default(SignResponse);
                    }
                    finally
                    {
                        if (response_ != null)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
            }
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module on whose behalf the plaintext will be encrypted. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <param name="payload">The data to be encrypted.</param>
        /// <returns>OK</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        public Task<EncryptResponse> EncryptAsync(string api_version, string name, string genid, EncryptRequest payload)
        {
            return EncryptAsync(api_version, name, genid, payload, CancellationToken.None);
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module on whose behalf the plaintext will be encrypted. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <param name="payload">The data to be encrypted.</param>
        /// <returns>OK</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        public async Task<EncryptResponse> EncryptAsync(string api_version, string name, string genid, EncryptRequest payload, CancellationToken cancellationToken)
        {
            if (name == null)
                throw new ArgumentNullException("name");

            if (genid == null)
                throw new ArgumentNullException("genid");

            if (api_version == null)
                throw new ArgumentNullException("api_version");

            var urlBuilder_ = new StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/modules/{name}/genid/{genid}/encrypt?");
            urlBuilder_.Replace("{name}", WebUtility.UrlEncode(ConvertToString(name, CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{genid}", WebUtility.UrlEncode(ConvertToString(genid, CultureInfo.InvariantCulture)));
            urlBuilder_.Append("api-version=").Append(WebUtility.UrlEncode(ConvertToString(api_version, CultureInfo.InvariantCulture))).Append("&");
            urlBuilder_.Length--;

            var client_ = _httpClient;
            try
            {
                using (var request_ = new HttpRequestMessage())
                {
                    var content_ = new StringContent(JsonConvert.SerializeObject(payload, _settings.Value));
                    content_.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new HttpMethod("POST");
                    request_.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new Uri(url_, UriKind.RelativeOrAbsolute);
                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(EncryptResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<EncryptResponse>(responseData_, _settings.Value);
                                return result_;
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }
                        }
                        else if (status_ == "404")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Not Found", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Error", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }

                        return default(EncryptResponse);
                    }
                    finally
                    {
                        if (response_ != null)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
            }
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module on whose behalf the ciphertext will be decrypted. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <param name="payload">The data to be decrypted.</param>
        /// <returns>OK</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        public Task<DecryptResponse> DecryptAsync(string api_version, string name, string genid, DecryptRequest payload)
        {
            return DecryptAsync(api_version, name, genid, payload, CancellationToken.None);
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module on whose behalf the ciphertext will be decrypted. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <param name="payload">The data to be decrypted.</param>
        /// <returns>OK</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        public async Task<DecryptResponse> DecryptAsync(string api_version, string name, string genid, DecryptRequest payload, CancellationToken cancellationToken)
        {
            if (name == null)
                throw new ArgumentNullException("name");

            if (genid == null)
                throw new ArgumentNullException("genid");

            if (api_version == null)
                throw new ArgumentNullException("api_version");

            var urlBuilder_ = new StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/modules/{name}/genid/{genid}/decrypt?");
            urlBuilder_.Replace("{name}", WebUtility.UrlEncode(ConvertToString(name, CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{genid}", WebUtility.UrlEncode(ConvertToString(genid, CultureInfo.InvariantCulture)));
            urlBuilder_.Append("api-version=").Append(WebUtility.UrlEncode(ConvertToString(api_version, CultureInfo.InvariantCulture))).Append("&");
            urlBuilder_.Length--;

            var client_ = _httpClient;
            try
            {
                using (var request_ = new HttpRequestMessage())
                {
                    var content_ = new StringContent(JsonConvert.SerializeObject(payload, _settings.Value));
                    content_.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new HttpMethod("POST");
                    request_.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new Uri(url_, UriKind.RelativeOrAbsolute);
                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(DecryptResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<DecryptResponse>(responseData_, _settings.Value);
                                return result_;
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }
                        }
                        else if (status_ == "404")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Not Found", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Error", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }

                        return default(DecryptResponse);
                    }
                    finally
                    {
                        if (response_ != null)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
            }
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module to get certificate. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <returns>Ok</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        public Task<CertificateResponse> CreateIdentityCertificateAsync(string api_version, string name, string genid)
        {
            return CreateIdentityCertificateAsync(api_version, name, genid, CancellationToken.None);
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module to get certificate. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <returns>Ok</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        public async Task<CertificateResponse> CreateIdentityCertificateAsync(string api_version, string name, string genid, CancellationToken cancellationToken)
        {
            if (name == null)
                throw new ArgumentNullException("name");

            if (genid == null)
                throw new ArgumentNullException("genid");

            if (api_version == null)
                throw new ArgumentNullException("api_version");

            var urlBuilder_ = new StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/modules/{name}/genid/{genid}/certificate/identity?");
            urlBuilder_.Replace("{name}", WebUtility.UrlEncode(ConvertToString(name, CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{genid}", WebUtility.UrlEncode(ConvertToString(genid, CultureInfo.InvariantCulture)));
            urlBuilder_.Append("api-version=").Append(WebUtility.UrlEncode(ConvertToString(api_version, CultureInfo.InvariantCulture))).Append("&");
            urlBuilder_.Length--;

            var client_ = _httpClient;
            try
            {
                using (var request_ = new HttpRequestMessage())
                {
                    request_.Content = new StringContent(string.Empty, Encoding.UTF8, "application/json");
                    request_.Method = new HttpMethod("POST");
                    request_.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new Uri(url_, UriKind.RelativeOrAbsolute);
                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(CertificateResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<CertificateResponse>(responseData_, _settings.Value);
                                return result_;
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }
                        }
                        else if (status_ == "404")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Not Found", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Error", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }

                        return default(CertificateResponse);
                    }
                    finally
                    {
                        if (response_ != null)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
            }
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module to get certificate. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <param name="request">Parameters for certificate creation.</param>
        /// <returns>Ok</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        public Task<CertificateResponse> CreateServerCertificateAsync(string api_version, string name, string genid, ServerCertificateRequest request)
        {
            return CreateServerCertificateAsync(api_version, name, genid, request, CancellationToken.None);
        }

        /// <param name="api_version">The version of the API.</param>
        /// <param name="name">The name of the module to get certificate. (urlencoded)</param>
        /// <param name="genid">The generation identifier for the module as generated by IoT Hub.</param>
        /// <param name="request">Parameters for certificate creation.</param>
        /// <returns>Ok</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        public async Task<CertificateResponse> CreateServerCertificateAsync(string api_version, string name, string genid, ServerCertificateRequest request, CancellationToken cancellationToken)
        {
            if (name == null)
                throw new ArgumentNullException("name");

            if (genid == null)
                throw new ArgumentNullException("genid");

            if (api_version == null)
                throw new ArgumentNullException("api_version");

            var urlBuilder_ = new StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/modules/{name}/genid/{genid}/certificate/server?");
            urlBuilder_.Replace("{name}", WebUtility.UrlEncode(ConvertToString(name, CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{genid}", WebUtility.UrlEncode(ConvertToString(genid, CultureInfo.InvariantCulture)));
            urlBuilder_.Append("api-version=").Append(WebUtility.UrlEncode(ConvertToString(api_version, CultureInfo.InvariantCulture))).Append("&");
            urlBuilder_.Length--;

            var client_ = _httpClient;
            try
            {
                using (var request_ = new HttpRequestMessage())
                {
                    var content_ = new StringContent(JsonConvert.SerializeObject(request, _settings.Value));
                    content_.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new HttpMethod("POST");
                    request_.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new Uri(url_, UriKind.RelativeOrAbsolute);
                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "201")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(CertificateResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<CertificateResponse>(responseData_, _settings.Value);
                                return result_;
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }
                        }
                        else if (status_ == "404")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Not Found", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Error", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }

                        return default(CertificateResponse);
                    }
                    finally
                    {
                        if (response_ != null)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
            }
        }

        /// <param name="api_version">The version of the API.</param>
        /// <returns>Ok</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        public Task<TrustBundleResponse> TrustBundleAsync(string api_version)
        {
            return TrustBundleAsync(api_version, CancellationToken.None);
        }

        /// <param name="api_version">The version of the API.</param>
        /// <returns>Ok</returns>
        /// <exception cref="IoTEdgedException">A server side error occurred.</exception>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        public async Task<TrustBundleResponse> TrustBundleAsync(string api_version, CancellationToken cancellationToken)
        {
            if (api_version == null)
                throw new ArgumentNullException("api_version");

            var urlBuilder_ = new StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/trust-bundle?");
            urlBuilder_.Append("api-version=").Append(WebUtility.UrlEncode(ConvertToString(api_version, CultureInfo.InvariantCulture))).Append("&");
            urlBuilder_.Length--;

            var client_ = _httpClient;
            try
            {
                using (var request_ = new HttpRequestMessage())
                {
                    request_.Method = new HttpMethod("GET");
                    request_.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new Uri(url_, UriKind.RelativeOrAbsolute);
                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200")
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(TrustBundleResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<TrustBundleResponse>(responseData_, _settings.Value);
                                return result_;
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(ErrorResponse);
                            try
                            {
                                result_ = JsonConvert.DeserializeObject<ErrorResponse>(responseData_, _settings.Value);
                            }
                            catch (Exception exception_)
                            {
                                throw new IoTEdgedException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }

                            throw new IoTEdgedException<ErrorResponse>("Error", (int)response_.StatusCode, responseData_, headers_, result_, null);
                        }

                        return default(TrustBundleResponse);
                    }
                    finally
                    {
                        if (response_ != null)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
            }
        }

        partial void UpdateJsonSerializerSettings(JsonSerializerSettings settings);

        partial void PrepareRequest(HttpClient client, HttpRequestMessage request, string url);

        partial void PrepareRequest(HttpClient client, HttpRequestMessage request, StringBuilder urlBuilder);

        partial void ProcessResponse(HttpClient client, HttpResponseMessage response);

        private string ConvertToString(object value, CultureInfo cultureInfo)
        {
            if (value is Enum)
            {
                string name = Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field = IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field != null)
                    {
                        var attribute = CustomAttributeExtensions.GetCustomAttribute(field, typeof(EnumMemberAttribute))
                            as EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value;
                        }
                    }
                }
            }
            else if (value is byte[])
            {
                return Convert.ToBase64String((byte[])value);
            }
            else if (value.GetType().IsArray)
            {
                var array = Enumerable.OfType<object>((Array)value);
                return string.Join(",", Enumerable.Select(array, o => ConvertToString(o, cultureInfo)));
            }

            return Convert.ToString(value, cultureInfo);
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class SignRequest : INotifyPropertyChanged
    {
        private string _keyId;
        private SignRequestAlgo _algo;
        private byte[] _data;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>Sign algorithm to be used.</summary>
        [JsonProperty("algo", Required = Required.Always)]
        [JsonConverter(typeof(StringEnumConverter))]
        public SignRequestAlgo Algo
        {
            get { return _algo; }
            set
            {
                if (_algo != value)
                {
                    _algo = value;
                    RaisePropertyChanged();
                }
            }
        }

        /// <summary>Data to be signed.</summary>
        [JsonProperty("data", Required = Required.Always)]
        public byte[] Data
        {
            get { return _data; }
            set
            {
                if (_data != value)
                {
                    _data = value;
                    RaisePropertyChanged();
                }
            }
        }

        /// <summary>Name of key to perform sign operation.</summary>
        [JsonProperty("keyId", Required = Required.Always)]
        public string KeyId
        {
            get { return _keyId; }
            set
            {
                if (_keyId != value)
                {
                    _keyId = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static SignRequest FromJson(string data)
        {
            return JsonConvert.DeserializeObject<SignRequest>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class SignResponse : INotifyPropertyChanged
    {
        private byte[] _digest;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>Signature of the data.</summary>
        [JsonProperty("digest", Required = Required.Always)]
        public byte[] Digest
        {
            get { return _digest; }
            set
            {
                if (_digest != value)
                {
                    _digest = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static SignResponse FromJson(string data)
        {
            return JsonConvert.DeserializeObject<SignResponse>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class EncryptRequest : INotifyPropertyChanged
    {
        private byte[] _plaintext;
        private byte[] _initializationVector;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>An initialization vector used to encrypt the data.</summary>
        [JsonProperty("initializationVector", Required = Required.Always)]
        public byte[] InitializationVector
        {
            get { return _initializationVector; }
            set
            {
                if (_initializationVector != value)
                {
                    _initializationVector = value;
                    RaisePropertyChanged();
                }
            }
        }

        /// <summary>The data to be encrypted.</summary>
        [JsonProperty("plaintext", Required = Required.Always)]
        public byte[] Plaintext
        {
            get { return _plaintext; }
            set
            {
                if (_plaintext != value)
                {
                    _plaintext = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static EncryptRequest FromJson(string data)
        {
            return JsonConvert.DeserializeObject<EncryptRequest>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class EncryptResponse : INotifyPropertyChanged
    {
        private byte[] _ciphertext;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>The encrypted form of the data encoded in base 64.</summary>
        [JsonProperty("ciphertext", Required = Required.Always)]
        public byte[] Ciphertext
        {
            get { return _ciphertext; }
            set
            {
                if (_ciphertext != value)
                {
                    _ciphertext = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static EncryptResponse FromJson(string data)
        {
            return JsonConvert.DeserializeObject<EncryptResponse>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class DecryptRequest : INotifyPropertyChanged
    {
        private byte[] _ciphertext;
        private byte[] _initializationVector;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>The data to be decrypted.</summary>
        [JsonProperty("ciphertext", Required = Required.Always)]
        public byte[] Ciphertext
        {
            get { return _ciphertext; }
            set
            {
                if (_ciphertext != value)
                {
                    _ciphertext = value;
                    RaisePropertyChanged();
                }
            }
        }

        /// <summary>An initialization vector used to decrypt the data.</summary>
        [JsonProperty("initializationVector", Required = Required.Always)]
        public byte[] InitializationVector
        {
            get { return _initializationVector; }
            set
            {
                if (_initializationVector != value)
                {
                    _initializationVector = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static DecryptRequest FromJson(string data)
        {
            return JsonConvert.DeserializeObject<DecryptRequest>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class DecryptResponse : INotifyPropertyChanged
    {
        private byte[] _plaintext;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>The decrypted form of the data encoded in base 64.</summary>
        [JsonProperty("plaintext", Required = Required.Always)]
        public byte[] Plaintext
        {
            get { return _plaintext; }
            set
            {
                if (_plaintext != value)
                {
                    _plaintext = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static DecryptResponse FromJson(string data)
        {
            return JsonConvert.DeserializeObject<DecryptResponse>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class ServerCertificateRequest : INotifyPropertyChanged
    {
        private string _commonName;
        private DateTime _expiration;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>Subject common name</summary>
        [JsonProperty("commonName", Required = Required.Always)]
        public string CommonName
        {
            get { return _commonName; }
            set
            {
                if (_commonName != value)
                {
                    _commonName = value;
                    RaisePropertyChanged();
                }
            }
        }

        /// <summary>Certificate expiration date-time (ISO 8601)</summary>
        [JsonProperty("expiration", Required = Required.Always)]
        public DateTime Expiration
        {
            get { return _expiration; }
            set
            {
                if (_expiration != value)
                {
                    _expiration = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static ServerCertificateRequest FromJson(string data)
        {
            return JsonConvert.DeserializeObject<ServerCertificateRequest>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class CertificateResponse : INotifyPropertyChanged
    {
        private PrivateKey _privateKey = new PrivateKey();
        private string _certificate;
        private DateTime _expiration;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>Base64 encoded PEM formatted byte array containing the certificate and its chain.</summary>
        [JsonProperty("certificate", Required = Required.Always)]
        public string Certificate
        {
            get { return _certificate; }
            set
            {
                if (_certificate != value)
                {
                    _certificate = value;
                    RaisePropertyChanged();
                }
            }
        }

        /// <summary>Certificate expiration date-time (ISO 8601)</summary>
        [JsonProperty("expiration", Required = Required.Always)]
        public DateTime Expiration
        {
            get { return _expiration; }
            set
            {
                if (_expiration != value)
                {
                    _expiration = value;
                    RaisePropertyChanged();
                }
            }
        }

        [JsonProperty("privateKey", Required = Required.Always)]
        public PrivateKey PrivateKey
        {
            get { return _privateKey; }
            set
            {
                if (_privateKey != value)
                {
                    _privateKey = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static CertificateResponse FromJson(string data)
        {
            return JsonConvert.DeserializeObject<CertificateResponse>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class TrustBundleResponse : INotifyPropertyChanged
    {
        private string _certificate;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>Base64 encoded PEM formatted byte array containing the trusted certificates.</summary>
        [JsonProperty("certificate", Required = Required.Always)]
        public string Certificate
        {
            get { return _certificate; }
            set
            {
                if (_certificate != value)
                {
                    _certificate = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static TrustBundleResponse FromJson(string data)
        {
            return JsonConvert.DeserializeObject<TrustBundleResponse>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class PrivateKey : INotifyPropertyChanged
    {
        private PrivateKeyType _type;
        private string _ref;
        private string _bytes;

        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>Base64 encoded PEM formatted byte array</summary>
        [JsonProperty("bytes", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Bytes
        {
            get { return _bytes; }
            set
            {
                if (_bytes != value)
                {
                    _bytes = value;
                    RaisePropertyChanged();
                }
            }
        }

        /// <summary>Reference to private key.</summary>
        [JsonProperty("ref", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Ref
        {
            get { return _ref; }
            set
            {
                if (_ref != value)
                {
                    _ref = value;
                    RaisePropertyChanged();
                }
            }
        }

        /// <summary>Indicates format of the key (present in PEM formatted bytes or a reference)</summary>
        [JsonProperty("type", Required = Required.Always)]
        [JsonConverter(typeof(StringEnumConverter))]
        public PrivateKeyType Type
        {
            get { return _type; }
            set
            {
                if (_type != value)
                {
                    _type = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static PrivateKey FromJson(string data)
        {
            return JsonConvert.DeserializeObject<PrivateKey>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class ErrorResponse : INotifyPropertyChanged
    {
        private string _message;

        public event PropertyChangedEventHandler PropertyChanged;

        [JsonProperty("message", Required = Required.Always)]
        public string Message
        {
            get { return _message; }
            set
            {
                if (_message != value)
                {
                    _message = value;
                    RaisePropertyChanged();
                }
            }
        }

        public static ErrorResponse FromJson(string data)
        {
            return JsonConvert.DeserializeObject<ErrorResponse>(data);
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }

        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum SignRequestAlgo
    {
        [EnumMember(Value = "HMACSHA256")]
        HMACSHA256 = 0,
    }

    [GeneratedCode("NJsonSchema", "9.10.46.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum PrivateKeyType
    {
        [EnumMember(Value = "ref")]
        Ref = 0,

        [EnumMember(Value = "key")]
        Key = 1,
    }

    [GeneratedCode("NSwag", "11.17.6.0 (NJsonSchema v9.10.46.0 (Newtonsoft.Json v9.0.0.0))")]
    public partial class IoTEdgedException : Exception
    {
        public IoTEdgedException(string message, int statusCode, string response, Dictionary<string, IEnumerable<string>> headers, Exception innerException)
            : base(message, innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public Dictionary<string, IEnumerable<string>> Headers { get; private set; }

        public string Response { get; private set; }

        public int StatusCode { get; private set; }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [GeneratedCode("NSwag", "11.17.6.0 (NJsonSchema v9.10.46.0 (Newtonsoft.Json v9.0.0.0))")]
    public partial class IoTEdgedException<TResult> : IoTEdgedException
    {
        public IoTEdgedException(string message, int statusCode, string response, Dictionary<string, IEnumerable<string>> headers, TResult result, Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }

        public TResult Result { get; private set; }
    }
}
